spring:
  config:
    import: application-common_private.yml, application-production_private.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
