server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/sprinter?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    baseline-on-migrate: true
    url: jdbc:mysql://${DB_URL}:3306/sprinter?serverTimezone=UTC&characterEncoding=UTF-8
    baseline-version: 1
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  graphql:
    graphiql.enabled: true
    schema.printer.enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      org:
        hibernate:
          format_sql: true
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
    show-sql: false
    generate-ddl: false

  config:
    activate:
      on-profile: prod
jwt:
  secret-key: ${SECRET_KEY}

aws:
  s3-bucket:
    sprinter:
      folder: ${SPRINTER_FOLDER}
      bucket: ${SPRINTER_BUCKET}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${REGION}
