server:
  port: 8080

spring:
  graphql:
    graphiql.enabled: true
    schema.printer.enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sprinter?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sprinter

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      org:
        hibernate:
          format_sql: true
          envers:
            revision_field_name: rev_id
            audit_table_suffix: _histories
            modified_flag_suffix: _modified
            store_data_at_delete: true
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
    show-sql: false
    generate-ddl: false

  flyway:
    baseline-on-migrate: true
    url: jdbc:mysql://127.0.0.1:3306/sprinter?serverTimezone=UTC&characterEncoding=UTF-8
    baseline-version: 1
    user: root
    password: sprinter
    enabled: true
jwt:
  secret-key: this_is_32_byte_local_secret_key

dgs:
  graphql:
    extensions:
      scalars:
        numbers:
          enabled: true
        time-dates:
          enabled: true
    schema-locations:
      - classpath*:schema/**/*.graphql*

aws:
  s3-bucket:
    sprinter:
      folder: local_sprinter_folder
      bucket: local_sprinter_bucket
    access-key: local_access_key
    secret-key: local_secret_key
    region: local_region
  s3:
    minio:
      region: ap-northeast-2
      endpoint: "http://localhost:9094"
      accessKey: "1234567890"
      secretKey: "1234567890"
    bucket:
      sprinter-img-bucket: sprinter-img-bucket
