
server:
  port: 9090

spring:
  graphql:
    graphiql.enabled: true
    schema.printer.enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/sprinter?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      org:
        hibernate:
          format_sql: true
          envers:
            revision_field_name: rev_id
            audit_table_suffix: _histories
            modified_flag_suffix: _modified
            store_data_at_delete: true
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
    show-sql: false
    generate-ddl: false

  profiles:
    active: local