version: '3'

networks:
  network:
    driver: bridge

volumes:
  sprinter-mysql:
  sprinter-redis:

services:
  mysql:
    container_name: sprinter-mysql
    image: ubuntu/mysql:edge
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    networks:
      - network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sprinter
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=sprinter1234
      - MYSQL_ROOT_PASSWORD=sprinter1234
      - TZ=UTC
    volumes:
      - sprinter-mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  redis:
    container_name: sprinter-redis
    image: redis:4-alpine
    networks:
      - network
    ports:
      - "6379:6379"
    volumes:
      - sprinter-redis:/data
